var searchPage = {}
module.exports = {
    before: browser => {
        searchPage=browser.page.yoodlizePage()
        searchPage
            .navigate()
    },
    after: browser => {
        searchPage.end()
    },
    'See all test': browser => {
        browser
            .useXpath()
            .click('//div[contains(text(),"RECREATIONAL VEHICLE")]/a/div')
            .waitForElementVisible('//div[@class="sc-jKVCRD jSqgxr"]')
            .verify.containsText('//div[@class="sc-jKVCRD jSqgxr"]', 'Recreational Vehicles')
            .back()
            .click('//div[contains(text(),"OUTDOOR GEAR")]/a/div')
            .waitForElementVisible('//div[@class="sc-jKVCRD jSqgxr"]')
            .verify.containsText('//div[@class="sc-jKVCRD jSqgxr"]', 'Outdoor Gear')
            .back()
            .click('//div[contains(text(),"ELECTRONICS")]/a/div')
            .waitForElementVisible('//div[@class="sc-jKVCRD jSqgxr"]')
            .verify.containsText('//div[@class="sc-jKVCRD jSqgxr"]', 'Electronics')
            .back()
            .click('//div[contains(text(),"PARTY & WEDDING EQUIPMENT")]/a/div')
            .waitForElementVisible('//div[@class="sc-jKVCRD jSqgxr"]')
            .verify.containsText('//div[@class="sc-jKVCRD jSqgxr"]', 'Party & Wedding Equipment')
            .back()
            .click('//div[contains(text(),"TOOLS")]/a/div')
            .waitForElementVisible('//div[@class="sc-jKVCRD jSqgxr"]')
            .verify.containsText('//div[@class="sc-jKVCRD jSqgxr"]', 'Tools')
            .back()
            .click('//div[contains(text(),"CLOTHING")]/a/div')
            .waitForElementVisible('//div[@class="sc-jKVCRD jSqgxr"]')
            .verify.containsText('//div[@class="sc-jKVCRD jSqgxr"]', 'Clothing')
            .back()
            .click('//div[contains(text(),"HOME & KITCHEN")]/a/div')
            .waitForElementVisible('//div[@class="sc-jKVCRD jSqgxr"]')
            .verify.containsText('//div[@class="sc-jKVCRD jSqgxr"]', 'Home and Kitchen')
            .back()
            .click('//div[contains(text(),"TOYS & GAMES")]/a/div')
            .waitForElementVisible('//div[@class="sc-jKVCRD jSqgxr"]')
            .verify.containsText('//div[@class="sc-jKVCRD jSqgxr"]', 'Toys and Games')
            .back()
            .click('//div[contains(text(),"LAWN & GARDEN")]/a/div')
            .waitForElementVisible('//div[@class="sc-jKVCRD jSqgxr"]')
            .verify.containsText('//div[@class="sc-jKVCRD jSqgxr"]', 'Lawn and Garden')
            .back()
            .click('//div[contains(text(),"SPORTING GOODS")]/a/div')
            .waitForElementVisible('//div[@class="sc-jKVCRD jSqgxr"]')
            .verify.containsText('//div[@class="sc-jKVCRD jSqgxr"]', 'Sporting Equipment')
            .back()
            .click('//div[contains(text(),"DVDs & VIDEO GAMES")]/a/div')
            .waitForElementVisible('//div[@class="sc-jKVCRD jSqgxr"]')
            .verify.containsText('//div[@class="sc-jKVCRD jSqgxr"]', 'DVDs')
            .back()
            .click('//div[contains(text(),"VENUES")]/a/div')
            .waitForElementVisible('//div[@class="sc-jKVCRD jSqgxr"]')
            .verify.containsText('//div[@class="sc-jKVCRD jSqgxr"]', 'Venues')
            .back()
            .click('//div[contains(text(),"MUSIC")]/a/div')
            .waitForElementVisible('//div[@class="sc-jKVCRD jSqgxr"]')
            .verify.containsText('//div[@class="sc-jKVCRD jSqgxr"]', 'Music')
            .back()
            .click('//div[contains(text(),"BUSINESS EQUIPMENT")]/a/div')
            .waitForElementVisible('//div[@class="sc-jKVCRD jSqgxr"]')
            .verify.containsText('//div[@class="sc-jKVCRD jSqgxr"]', 'Business Equipment')
            .back()
            .click('//div[contains(text(),"MISC")]/a/div')
            .waitForElementVisible('//div[@class="sc-jKVCRD jSqgxr"]')
            .verify.containsText('//div[@class="sc-jKVCRD jSqgxr"]', 'Misc')
            .back()
            .click('//div[@class="f-center-start h-45"]/div[contains(text(),"TOOLS")]')
            .waitForElementVisible('//div[@class="sc-jKVCRD jSqgxr"]')
            .verify.containsText('//div[@class="sc-jKVCRD jSqgxr"]', 'Tools')
            .back()
            .click('//div[@class="f-center-start h-45"]/div[contains(text(),"OUTDOOR GEAR")]')
            .waitForElementVisible('//div[@class="sc-jKVCRD jSqgxr"]')
            .verify.containsText('//div[@class="sc-jKVCRD jSqgxr"]', 'Outdoor Gear')
            .back()
            .click('//div[@class="f-center-start h-45"]/div[contains(text(),"ELECTRONICS")]')
            .waitForElementVisible('//div[@class="sc-jKVCRD jSqgxr"]')
            .verify.containsText('//div[@class="sc-jKVCRD jSqgxr"]', 'Electronics')
            .back()
            .click('//div[@class="f-center-start h-45"]/div[contains(text(),"PARTY & WEDDING")]')
            .waitForElementVisible('//div[@class="sc-jKVCRD jSqgxr"]')
            .verify.containsText('//div[@class="sc-jKVCRD jSqgxr"]', 'Party & Wedding Equipment')
            .back()
            .click('//div[@class="f-center-start h-45"]/div[contains(text(),"RECREATIONAL VEHICLES")]')
            .waitForElementVisible('//div[@class="sc-jKVCRD jSqgxr"]')
            .verify.containsText('//div[@class="sc-jKVCRD jSqgxr"]', 'Recreational Vehicles')
            .back()
            .click('//div[@class="f-center-start h-45"]/div[contains(text(),"CLOTHING")]')
            .waitForElementVisible('//div[@class="sc-jKVCRD jSqgxr"]')
            .verify.containsText('//div[@class="sc-jKVCRD jSqgxr"]', 'Clothing')
            .back()
            .click('//div[@class="f-center-start h-45"]/div[contains(text(),"HOME & KITCHEN")]')
            .waitForElementVisible('//div[@class="sc-jKVCRD jSqgxr"]')
            .verify.containsText('//div[@class="sc-jKVCRD jSqgxr"]', 'Home and Kitchen')
            .back()
            .click('//div[@class="f-center-start h-45"]/div[contains(text(),"TOYS & GAMES")]')
            .waitForElementVisible('//div[@class="sc-jKVCRD jSqgxr"]')
            .verify.containsText('//div[@class="sc-jKVCRD jSqgxr"]', 'Toys and Games')
            .back()
            .click('//div[@class="f-center-start h-45"]/div[contains(text(),"LAWN & GARDEN")]')
            .waitForElementVisible('//div[@class="sc-jKVCRD jSqgxr"]')
            .verify.containsText('//div[@class="sc-jKVCRD jSqgxr"]', 'Lawn and Garden')
            .back()
            .click('//div[@class="f-center-start h-45"]/div[contains(text(),"SPORTING GOODS")]')
            .waitForElementVisible('//div[@class="sc-jKVCRD jSqgxr"]')
            .verify.containsText('//div[@class="sc-jKVCRD jSqgxr"]', 'Sporting Equipment')
            .back()
            .click('//div[@class="f-center-start h-45"]/div[contains(text(),"DVDS & VIDEO GAMES")]')
            .waitForElementVisible('//div[@class="sc-jKVCRD jSqgxr"]')
            .verify.containsText('//div[@class="sc-jKVCRD jSqgxr"]', 'DVDs')
            .back()
            .click('//div[@class="f-center-start h-45"]/div[contains(text(),"VENUES")]')
            .waitForElementVisible('//div[@class="sc-jKVCRD jSqgxr"]')
            .verify.containsText('//div[@class="sc-jKVCRD jSqgxr"]', 'Venues')
            .back()
            .click('//div[@class="f-center-start h-45"]/div[contains(text(),"MUSIC")]')
            .waitForElementVisible('//div[@class="sc-jKVCRD jSqgxr"]')
            .verify.containsText('//div[@class="sc-jKVCRD jSqgxr"]', 'Music')
            .back()
            .click('//div[@class="f-center-start h-45"]/div[contains(text(),"MISC")]')
            .waitForElementVisible('//div[@class="sc-jKVCRD jSqgxr"]')
            .verify.containsText('//div[@class="sc-jKVCRD jSqgxr"]', 'Misc')
            .back()

    }

}