var testPage = {}
module.exports = {
    before: browser => {
        testPage = browser.page.yoodlizePageObject()
        testPage
            .navigate()
    },
    after: browser => {
        testPage.end()
    },
    'See all test': browser => {
        testPage
            .click('@recVehicleSeeAll')
            .waitForElementVisible('@searchCategory')
            .verify.containsText('@searchCategory', 'Recreational Vehicles')
            .api.back()
        testPage.click('@outGearSeeAll')
            .waitForElementVisible('@searchCategory')
            .verify.containsText('@searchCategory', 'Outdoor Gear')
            .api.back()
        testPage.click('@electronicsSeeAll')
            .waitForElementVisible('@searchCategory')
            .verify.containsText('@searchCategory', 'Electronics')
            .api.back()
        testPage.click('@partySeeAll')
            .waitForElementVisible('@searchCategory')
            .verify.containsText('@searchCategory', 'Party & Wedding Equipment')
            .api.back()
        testPage.click('@toolsSeeAll')
            .waitForElementVisible('@searchCategory')
            .verify.containsText('@searchCategory', 'Tools')
            .api.back()
        testPage.click('@clothingSeeAll')
            .waitForElementVisible('@searchCategory')
            .verify.containsText('@searchCategory', 'Clothing')
            .api.back()
        testPage.click('@homeSeeAll')
            .waitForElementVisible('@searchCategory')
            .verify.containsText('@searchCategory', 'Home and Kitchen')
            .api.back()
        testPage.click('@toysSeeAll')
            .waitForElementVisible('@searchCategory')
            .verify.containsText('@searchCategory', 'Toys and Games')
            .api.back()
        testPage.click('@lawnSeeAll')
            .waitForElementVisible('@searchCategory')
            .verify.containsText('@searchCategory', 'Lawn and Garden')
            .api.back()
        testPage.click('@sportSeeAll')
            .waitForElementVisible('@searchCategory')
            .verify.containsText('@searchCategory', 'Sporting Equipment')
            .api.back()
        testPage.click('@dvdSeeAll')
            .waitForElementVisible('@searchCategory')
            .verify.containsText('@searchCategory', 'DVDs')
            .api.back()
        testPage.click('@venuesSeeAll')
            .waitForElementVisible('@searchCategory')
            .verify.containsText('@searchCategory', 'Venues')
            .api.back()
        testPage.click('@musicSeeAll')
            .waitForElementVisible('@searchCategory')
            .verify.containsText('@searchCategory', 'Music')
            .api.back()
        testPage.click('@businessSeeAll')
            .waitForElementVisible('@searchCategory')
            .verify.containsText('@searchCategory', 'Business Equipment')
            .api.back()
        testPage.click('@miscSeeAll')
            .waitForElementVisible('@searchCategory')
            .verify.containsText('@searchCategory', 'Misc')
            .api.back()
        testPage.click('@toolsButton')
            .waitForElementVisible('@searchCategory')
            .verify.containsText('@searchCategory', 'Tools')
            .api.back()
        testPage.click('@outdoorButton')
            .waitForElementVisible('@searchCategory')
            .verify.containsText('@searchCategory', 'Outdoor Gear')
            .api.back()
        testPage.click('@electronicsButton')
            .waitForElementVisible('@searchCategory')
            .verify.containsText('@searchCategory', 'Electronics')
            .api.back()
        testPage.click('@partyButton')
            .waitForElementVisible('@searchCategory')
            .verify.containsText('@searchCategory', 'Party & Wedding Equipment')
            .api.back()
        testPage.click('@recVehiclesButton')
            .waitForElementVisible('@searchCategory')
            .verify.containsText('@searchCategory', 'Recreational Vehicles')
            .api.back()
        testPage.click('@clothingButton')
            .waitForElementVisible('@searchCategory')
            .verify.containsText('@searchCategory', 'Clothing')
            .api.back()
        testPage.click('@homeButton')
            .waitForElementVisible('@searchCategory')
            .verify.containsText('@searchCategory', 'Home and Kitchen')
            .api.back()
        testPage.click('@toysButton')
            .waitForElementVisible('@searchCategory')
            .verify.containsText('@searchCategory', 'Toys and Games')
            .api.back()
        testPage.click('@lawnButton')
            .waitForElementVisible('@searchCategory')
            .verify.containsText('@searchCategory', 'Lawn and Garden')
            .api.back()
        testPage.click('@sportButton')
            .waitForElementVisible('@searchCategory')
            .verify.containsText('@searchCategory', 'Sporting Equipment')
            .api.back()
        testPage.click('@dvdButton')
            .waitForElementVisible('@searchCategory')
            .verify.containsText('@searchCategory', 'DVDs')
            .api.back()
        testPage.click('@venuesButton')
            .waitForElementVisible('@searchCategory')
            .verify.containsText('@searchCategory', 'Venues')
            .api.back()
        testPage.click('@musicButton')
            .waitForElementVisible('@searchCategory')
            .verify.containsText('@searchCategory', 'Music')
            .api.back()
        testPage.click('@miscButton')
            .waitForElementVisible('@searchCategory')
            .verify.containsText('@searchCategory', 'Misc')
            .api.back()

    }

}