module.exports=[{
    loanType:'Home Purchase',
    propType:'Condo',
    city:'Los Angeles',
    loanProp:'Primary Home',
    newHome:'Yes',
    agent:'No',
    price:1000000,
    down:5000,
    credit:'Good',
    bankrupt:'Bankruptcy',
    addressOne:'123 ABC Drive',
    addressTwo:'DEF',
    addressThree:'Los Angeles',
    firstName:'Patrick',
    lastName:'Star',
    email:'patrick.star@bikbot.com',
    newHomeResult:'True',
    agentResult:'False'
},
    {loanType:'Home Equity',
    propType:'Multi Family Dwelling',
    city:'New York',
    loanProp:'Rental Property',
    newHome:'No',
    agent:'Yes',
    price:3000000,
    down:25000,
    credit:'Excellent',
    bankrupt:'oreclosure',
    addressOne:'876 Berry Drive',
    addressTwo:'Fruit',
    addressThree:'New York',
    firstName:'Sandy',
    lastName:'Cheeks',
    email:'sandy.cheeks@bikbot.com',
    newHomeResult:'False',
    agentResult:'True'
}
]